# Memoria y codificación
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# AndroidX
android.useAndroidX=true
android.enableJetifier=true

# Evitar el warning de compileSdk 35
android.suppressUnsupportedCompileSdk=35

# Desactivar la feature que te rompe el build en GitHub Actions (androidJdkImage + jlink)
android.experimental.androidJdkImage=false
