import React, { createContext, useContext, useState, useEffect } from 'react';

// 🌍 Diccionario completo de traducciones para la interfaz de usuario (ES, EN, FR)
const translations = {
  es: {
    // Menú y Navegación
    inicio: "Inicio",
    clientes: "Clientes",
    viviendas: "Viviendas",
    inspecciones: "Inspecciones",
    servicios: "Servicios",
    contratos: "Contratos",
    facturas: "Facturas",
    tecnicos: "Técnicos",
    dashboard: "Dashboard",
    ajustes: "Ajustes",
    perfil: "Perfil",

    // Generales / Dashboard
    bienvenida: "Bienvenido a tu panel de cliente",
    misViviendas: "Mis Viviendas",
    serviciosExtras: "Servicios Extras",
    cerrarSesion: "Cerrar Sesión",
    logout: "Cerrar Sesión",
    noHayDatos: "No hay registros disponibles.",
    cambiarIdioma: "Idioma",
    verDetalles: "Ver Detalles",
    estadoPendiente: "Pendiente",
    estadoAprobado: "Aprobado",
    estadoCompletado: "Completado",
    solicitarExtra: "Solicitar Servicio Extra",
    totalPagar: "Total a Pagar",
    direccion: "Dirección",
    cargandoPanel: "Cargando Panel...",
    panelDeControl: "Panel de Control",
    dashboardCliente: "Dashboard Cliente",
    operativo: "Operativo",
    trabajosExtrasDisponibles: "¡Trabajos Extras Disponibles!",
    tienes: "Tienes",
    trabajosRegistrados: "trabajos o informes extras registrados.",
    trabajoExtraFactura: "Trabajo Extra / Factura",
    verDetallesFotosFacturas: "Ver detalles y fotos en facturas",
    verFactura: "Ver Factura →",
    alertas: "Alertas",
    inspeccionesDiarias: "Inspecciones Diarias",
    configuracionSeguridadNotificaciones: "Configuración de Seguridad y Notificaciones",
    lun: "Lun",
    mar: "Mar",
    mie: "Mié",
    jue: "Jue",
    vie: "Vie",
    sab: "Sáb",
    dom: "Dom",

    // Crear Factura
    tituloNuevaFactura: "Nueva Factura / Extra",
    errorSeleccionarCliente: "Selecciona un cliente.",
    errorSeleccionarVivienda: "Selecciona una vivienda.",
    errorIntroducirImporte: "Introduce el importe.",
    errorCreandoFactura: "Error creando factura",
    facturaCreadaCorrectamente: "Factura creada correctamente",
    cliente: "Cliente",
    seleccionaCliente: "Selecciona un cliente...",
    vivienda: "Vivienda",
    seleccionaVivienda: "Selecciona una vivienda...",
    fecha: "Fecha",
    concepto: "Concepto",
    placeholderConcepto: "Descripción del servicio...",
    importe: "Importe",
    btnCrearFactura: "Crear Factura",

    // Perfil Cliente
    clienteDashboardCargando: "Cargando perfil...",
    clienteDashboardNoEncontrado: "No se encontró el perfil de cliente.",
    clientePerfilTitulo: "Mi Perfil",
    clienteDashboardNombre: "Nombre",
    clienteDashboardEmail: "Correo electrónico",
    clienteDashboardTelefono: "Teléfono",

    // Configuración y Seguridad
    configuracionYSeguridad: "Configuración y Seguridad",
    volver: "← Volver",
    preferenciasNotificacion: "Preferencias de Notificación",
    notifPushTitulo: "Notificaciones Push",
    notifPushSub: "Recibe avisos inmediatos en la app sobre tus inspecciones.",
    resumenCorreoTitulo: "Resumen por Correo",
    resumenCorreoSub: "Recibe informes y facturas directamente en tu email.",
    alertasCriticasTitulo: "Alertas de Incidencias Críticas",
    alertasCriticasSub: "Avisos urgentes de incidencias graves detectadas en viviendas.",
    seguridadCuenta: "Seguridad de la Cuenta",
    autenticacionDosPasosTitulo: "Autenticación en 2 Pasos (2FA)",
    autenticacionDosPasosSub: "Añade un nivel extra de seguridad al iniciar sesión.",
    contrasena: "Contraseña",
    ultimoCambioContrasena: "Último cambio hace más de 30 días",
    cambiar: "Cambiar",
    alertaCambiarContrasena: "Función para cambiar contraseña",
    cambiosGuardados: "✓ Cambios Guardados",
    guardarPreferencias: "Guardar Preferencias",

    // Lista de Contratos
    clienteListaTitulo: "Mis Contratos",
    cargandoContratos: "Cargando contratos...",
    usuarioNoAutenticado: "Usuario no autenticado.",
    errorIdentificarCliente: "No se pudo identificar el cliente asociado.",
    errorCargandoContratos: "Error cargando contratos.",
    errorInesperadoContratos: "Error inesperado cargando contratos.",
    reintentar: "Reintentar",
    clienteListaVacio: "No tienes contratos registrados.",
    servicioContratado: "Servicio contratado",

    // Ver Contrato Individual y Generación PDF
    contratoNoEncontrado: "Contrato no encontrado",
    clienteContratoCargando: "Cargando contrato...",
    noSePudoCargarContrato: "No se pudo cargar el contrato",
    compruebaTuConexion: "Comprueba tu conexión",
    clienteContratoTitulo: "Contrato del Cliente",
    clienteContratoDatosCliente: "Datos del Cliente",
    nombre: "Nombre",
    telefono: "Teléfono",
    clienteContratoDetalles: "Detalles del Contrato",
    tipoServicio: "Tipo de servicio: Cada",
    dias: "días",
    precioMensual: "Precio mensual",
    fechaInicio: "Fecha inicio",
    estado: "Estado",
    firmado: "Firmado",
    pendienteFirma: "Pendiente de firma",
    verContratoAntesFirmar: "📄 Ver contrato antes de firmar",
    firmaDelCliente: "Firma del Cliente",
    verCambiarFirma: "Ver / Cambiar Firma",
    enviarAlAdminBtn: "📤 Enviar contrato al Admin",
    enviando: "Enviando...",
    verContratoFirmadoPdf: "📄 Ver contrato firmado (PDF)",
    alertaDebesFirmar: "Debes firmar el contrato antes de enviarlo.",
    alertaErrorAdmin: "Error notificando al administrador: ",
    alertaContratoEnviado: "¡Contrato firmado enviado al administrador!",
    alertaNoPdfAdmin: "El administrador aún no ha generado el PDF.",
    clienteAccesoDenegado: "Acceso denegado o contrato no encontrado.",
    clienteContratoDireccion: "Dirección",

    // PDF del Contrato
    pdfTitulo: "CONTRATO DE PRESTACIÓN DE SERVICIOS",
    pdfNombreCliente: "Cliente",
    pdfDireccion: "Dirección",
    pdfTelefono: "Teléfono",
    pdfDetallesServicio: "DETALLES DEL SERVICIO",
    pdfTipoServicio: "Frecuencia",
    contratoCadaDias: "Cada",
    pdfFechaInicio: "Fecha de inicio",
    pdfPrecioMensual: "Precio mensual",
    pdfCondiciones: "CONDICIONES",
    pdfCondicionesTexto: "El prestador se compromete a realizar las inspecciones y servicios acordados según la frecuencia establecida, manteniendo la confidencialidad y el rigor profesional.",
    pdfFirmaCliente: "Firma del Cliente",
    pdfGenerado: "¡PDF generado y guardado con éxito!",
    pdfGenerando: "Generando PDF...",
    pdfGenerar: "Generar y Guardar PDF",
    errorSubirPdfStorage: "Error al subir el PDF a Storage: ",
    errorGenerarPdf: "Error al generar el PDF: ",

    // Visor de PDF
    pdfCargando: "Cargando PDF...",
    pdfNoGenerado: "No hay ningún archivo PDF generado para este contrato.",
    pdfTituloVista: "Contrato",
    pdfVolver: "Volver",
    pdfTituloIframe: "Visor de Contrato",
    pdfAbrirNuevaPestana: "Abrir en nueva pestaña",

    // Firma Dibujar
    firmaDelClienteTitulo: "Firma del Cliente",
    instruccionesFirma: "Dibuje su firma con el dedo dentro del recuadro blanco:",
    limpiar: "🗑️ Limpiar",
    guardarFirmaBtn: "💾 Guardar firma",
    alertaRealizarFirma: "Por favor, realiza tu firma antes de guardar.",
    alertaIdContratoValido: "Error: No se encontró un ID de contrato válido.",
    errorGuardandoFirma: "Error guardando la firma.",
    contratoFirmadoExito: "¡Contrato firmado con éxito!",
    errorGuardandoFirmaDetalle: "Error guardando la firma: ",

    // Ver Factura Individual
    facturaNoEncontrada: "No se encontró la factura",
    volverSimple: "Volver",
    estadoPagada: "PAGADA",
    estadoEnviadaCliente: "ENVIADA AL CLIENTE",
    servicioInspeccion: "Servicio / Inspección",
    facturaLabel: "Factura",
    evidenciaDelTrabajo: "Evidencia del Trabajo",
    materialesUtilizados: "Materiales utilizados:",
    tiempoEmpleado: "Tiempo empleado:",
    fotografiasInspeccion: "Fotografías de Inspección:",
    detalle: "Detalle",
    base: "Base",
    iva: "IVA",
    total: "Total",
    verPdf: "Ver PDF",
    noPdfGenerado: "Aún no hay PDF generado para esta factura.",

    // Lista de Facturas
    misFacturasTitulo: "Mis Facturas",
    cargandoFacturas: "Cargando facturas...",
    noHayFacturasRegistradas: "No hay facturas registradas.",
    estadoCancelada: "CANCELADA",
    estadoTrabajoCompletado: "TRABAJO COMPLETADO",
    estadoPendienteRevision: "PENDIENTE DE REVISIÓN",

    // Lista de Inspecciones
    cargandoListado: "Cargando Listado...",
    misInspeccionesInformesTitulo: "Mis Inspecciones e Informes",
    errorPerfilClienteAsociado: "No se encontró el perfil de cliente asociado.",
    errorCargarDatos: "Hubo un error al cargar los datos.",
    noHayInspeccionesInformes: "No hay inspecciones ni informes disponibles.",
    servicioExtraTrabajo: "🛠️ Servicio Extra / Trabajo",
    inspeccionLabel: "📋 Inspección",
    informeDisponible: "Informe disponible",
    detalleLabel: "Detalle:",
    verDetalleFlecha: "Ver detalle →",
    extraBadge: "⚡ EXTRA",

    // Ver Inspección / Informe
    cargandoInformacion: "Cargando información...",
    volverMisInformes: "← Volver a Mis Informes",
    informeNoEncontradoPermisos: "No se encontró el informe o no tienes permisos para verlo.",
    errorConexionCargarInformacion: "Error de conexión al cargar la información.",
    confirmarBorrarInforme: "¿Estás seguro de que quieres eliminar este informe de tu lista?",
    informeEliminadoExito: "Informe eliminado correctamente.",
    errorEliminarInforme: "No se pudo eliminar el informe.",
    informeLabel: "Informe",
    ubicacionVivienda: "Ubicación / Vivienda",
    direccionNoEspecificada: "Dirección no especificada",
    descripcionTrabajoObservaciones: "Descripción del Trabajo / Observaciones",
    sinObservacionesRegistradas: "Sin observaciones registradas.",
    materialesUsados: "Materiales usados:",
    tiempoEmpleadoLabel: "Tiempo empleado:",
    fotografiasAdjuntas: "Fotografías Adjuntas",
    noHayFotografiasInforme: "No hay fotografías adjuntas a este informe.",
    verInformePdf: "📄 Ver Informe PDF",
    borrarEsteInforme: "🗑️ Borrar este informe",
    fotoAmpliada: "Foto ampliada",
    cerrar: "Cerrar",
  },
  en: {
    // Menu & Navigation
    inicio: "Home",
    clientes: "Clients",
    viviendas: "Properties",
    inspecciones: "Inspections",
    servicios: "Services",
    contratos: "Contracts",
    facturas: "Invoices",
    tecnicos: "Technicians",
    dashboard: "Dashboard",
    ajustes: "Settings",
    perfil: "Profile",

    // General / Dashboard
    bienvenida: "Welcome to your client dashboard",
    misViviendas: "My Properties",
    serviciosExtras: "Extra Services",
    cerrarSesion: "Log Out",
    logout: "Log Out",
    noHayDatos: "No records available.",
    cambiarIdioma: "Language",
    verDetalles: "View Details",
    estadoPendiente: "Pending",
    estadoAprobado: "Approved",
    estadoCompletado: "Completed",
    solicitarExtra: "Request Extra Service",
    totalPagar: "Total Due",
    direccion: "Address",
    cargandoPanel: "Loading Dashboard...",
    panelDeControl: "Control Panel",
    dashboardCliente: "Client Dashboard",
    operativo: "Operational",
    trabajosExtrasDisponibles: "Extra Jobs Available!",
    tienes: "You have",
    trabajosRegistrados: "extra jobs or reports registered.",
    trabajoExtraFactura: "Extra Job / Invoice",
    verDetallesFotosFacturas: "View details and photos in invoices",
    verFactura: "View Invoice →",
    alertas: "Alerts",
    inspeccionesDiarias: "Daily Inspections",
    configuracionSeguridadNotificaciones: "Security and Notification Settings",
    lun: "Mon",
    mar: "Tue",
    mie: "Wed",
    jue: "Thu",
    vie: "Fri",
    sab: "Sat",
    dom: "Sun",

    // Create Invoice
    tituloNuevaFactura: "New Invoice / Extra",
    errorSeleccionarCliente: "Select a client.",
    errorSeleccionarVivienda: "Select a property.",
    errorIntroducirImporte: "Enter the amount.",
    errorCreandoFactura: "Error creating invoice",
    facturaCreadaCorrectamente: "Invoice created successfully",
    cliente: "Client",
    seleccionaCliente: "Select a client...",
    vivienda: "Property",
    seleccionaVivienda: "Select a property...",
    fecha: "Date",
    concepto: "Concept",
    placeholderConcepto: "Service description...",
    importe: "Amount",
    btnCrearFactura: "Create Invoice",

    // Perfil Cliente
    clienteDashboardCargando: "Loading profile...",
    clienteDashboardNoEncontrado: "Client profile not found.",
    clientePerfilTitulo: "My Profile",
    clienteDashboardNombre: "Name",
    clienteDashboardEmail: "Email",
    clienteDashboardTelefono: "Phone",

    // Configuration & Security
    configuracionYSeguridad: "Configuration & Security",
    volver: "← Back",
    preferenciasNotificacion: "Notification Preferences",
    notifPushTitulo: "Push Notifications",
    notifPushSub: "Receive immediate notices in the app about your inspections.",
    resumenCorreoTitulo: "Email Summary",
    resumenCorreoSub: "Receive reports and invoices directly in your email.",
    alertasCriticasTitulo: "Critical Incident Alerts",
    alertasCriticasSub: "Urgent notices of severe incidents detected in properties.",
    seguridadCuenta: "Account Security",
    autenticacionDosPasosTitulo: "Two-Factor Authentication (2FA)",
    autenticacionDosPasosSub: "Add an extra level of security when logging in.",
    contrasena: "Password",
    ultimoCambioContrasena: "Last changed more than 30 days ago",
    cambiar: "Change",
    alertaCambiarContrasena: "Password change feature",
    cambiosGuardados: "✓ Changes Saved",
    guardarPreferencias: "Save Preferences",

    // Contracts List
    clienteListaTitulo: "My Contracts",
    cargandoContratos: "Loading contracts...",
    usuarioNoAutenticado: "User not authenticated.",
    errorIdentificarCliente: "Could not identify the associated client.",
    errorCargandoContratos: "Error loading contracts.",
    errorInesperadoContratos: "Unexpected error loading contracts.",
    reintentar: "Retry",
    clienteListaVacio: "You have no registered contracts.",
    servicioContratado: "Contracted service",

    // View Contract Individual & PDF Generation
    contratoNoEncontrado: "Contract not found",
    clienteContratoCargando: "Loading contract...",
    noSePudoCargarContrato: "Could not load the contract",
    compruebaTuConexion: "Check your connection",
    clienteContratoTitulo: "Client Contract",
    clienteContratoDatosCliente: "Client Details",
    nombre: "Name",
    telefono: "Phone",
    clienteContratoDetalles: "Contract Details",
    tipoServicio: "Service type: Every",
    dias: "days",
    precioMensual: "Monthly price",
    fechaInicio: "Start date",
    estado: "Status",
    firmado: "Signed",
    pendienteFirma: "Pending signature",
    verContratoAntesFirmar: "📄 View contract before signing",
    firmaDelCliente: "Client Signature",
    verCambiarFirma: "View / Change Signature",
    enviarAlAdminBtn: "📤 Send contract to Admin",
    enviando: "Sending...",
    verContratoFirmadoPdf: "📄 View signed contract (PDF)",
    alertaDebesFirmar: "You must sign the contract before sending it.",
    alertaErrorAdmin: "Error notifying the administrator: ",
    alertaContratoEnviado: "Signed contract sent to the administrator!",
    alertaNoPdfAdmin: "The administrator has not generated the PDF yet.",
    clienteAccesoDenegado: "Access denied or contract not found.",
    clienteContratoDireccion: "Address",

    // PDF Generation
    pdfTitulo: "SERVICE AGREEMENT CONTRACT",
    pdfNombreCliente: "Client",
    pdfDireccion: "Address",
    pdfTelefono: "Phone",
    pdfDetallesServicio: "SERVICE DETAILS",
    pdfTipoServicio: "Frequency",
    contratoCadaDias: "Every",
    pdfFechaInicio: "Start date",
    pdfPrecioMensual: "Monthly price",
    pdfCondiciones: "CONDITIONS",
    pdfCondicionesTexto: "The provider agrees to perform the agreed inspections and services according to the established frequency, maintaining confidentiality and professional rigor.",
    pdfFirmaCliente: "Client Signature",
    pdfGenerado: "PDF generated and saved successfully!",
    pdfGenerando: "Generating PDF...",
    pdfGenerar: "Generate & Save PDF",
    errorSubirPdfStorage: "Error uploading PDF to Storage: ",
    errorGenerarPdf: "Error generating PDF: ",

    // PDF Viewer
    pdfCargando: "Loading PDF...",
    pdfNoGenerado: "No PDF file has been generated for this contract yet.",
    pdfTituloVista: "Contract",
    pdfVolver: "Back",
    pdfTituloIframe: "Contract Viewer",
    pdfAbrirNuevaPestana: "Open in new tab",

    // Signature Drawing
    firmaDelClienteTitulo: "Client Signature",
    instruccionesFirma: "Draw your signature with your finger inside the white box:",
    limpiar: "🗑️ Clear",
    guardarFirmaBtn: "💾 Save signature",
    alertaRealizarFirma: "Please sign before saving.",
    alertaIdContratoValido: "Error: No valid contract ID found.",
    errorGuardandoFirma: "Error saving signature.",
    contratoFirmadoExito: "Contract signed successfully!",
    errorGuardandoFirmaDetalle: "Error saving signature: ",

    // View Invoice Individual
    facturaNoEncontrada: "Invoice not found",
    volverSimple: "Back",
    estadoPagada: "PAID",
    estadoEnviadaCliente: "SENT TO CLIENT",
    servicioInspeccion: "Service / Inspection",
    facturaLabel: "Invoice",
    evidenciaDelTrabajo: "Work Evidence",
    materialesUtilizados: "Materials used:",
    tiempoEmpleado: "Time spent:",
    fotografiasInspeccion: "Inspection Photographs:",
    detalle: "Detail",
    base: "Subtotal",
    iva: "VAT",
    total: "Total",
    verPdf: "View PDF",
    noPdfGenerado: "No PDF generated for this invoice yet.",

    // Invoices List
    misFacturasTitulo: "My Invoices",
    cargandoFacturas: "Loading invoices...",
    noHayFacturasRegistradas: "No registered invoices found.",
    estadoCancelada: "CANCELLED",
    estadoTrabajoCompletado: "WORK COMPLETED",
    estadoPendienteRevision: "PENDING REVIEW",

    // Inspections List
    cargandoListado: "Loading List...",
    misInspeccionesInformesTitulo: "My Inspections & Reports",
    errorPerfilClienteAsociado: "Associated client profile not found.",
    errorCargarDatos: "There was an error loading data.",
    noHayInspeccionesInformes: "No inspections or reports available.",
    servicioExtraTrabajo: "🛠️ Extra Service / Job",
    inspeccionLabel: "📋 Inspection",
    informeDisponible: "Report available",
    detalleLabel: "Detail:",
    verDetalleFlecha: "View detail →",
    extraBadge: "⚡ EXTRA",

    // View Inspection / Report
    cargandoInformacion: "Loading information...",
    volverMisInformes: "← Back to My Reports",
    informeNoEncontradoPermisos: "Report not found or you don't have permission to view it.",
    errorConexionCargarInformacion: "Connection error loading information.",
    confirmarBorrarInforme: "Are you sure you want to delete this report from your list?",
    informeEliminadoExito: "Report deleted successfully.",
    errorEliminarInforme: "Could not delete the report.",
    informeLabel: "Report",
    ubicacionVivienda: "Location / Property",
    direccionNoEspecificada: "Address not specified",
    descripcionTrabajoObservaciones: "Job Description / Observations",
    sinObservacionesRegistradas: "No observations registered.",
    materialesUsados: "Materials used:",
    tiempoEmpleadoLabel: "Time spent:",
    fotografiasAdjuntas: "Attached Photographs",
    noHayFotografiasInforme: "No photographs attached to this report.",
    verInformePdf: "📄 View PDF Report",
    borrarEsteInforme: "🗑️ Delete this report",
    fotoAmpliada: "Enlarged photo",
    cerrar: "Close",
  },
  fr: {
    // Menu & Navigation
    inicio: "Accueil",
    clientes: "Clients",
    viviendas: "Propriétés",
    inspecciones: "Inspections",
    servicios: "Services",
    contratos: "Contrats",
    facturas: "Factures",
    tecnicos: "Techniciens",
    dashboard: "Tableau de bord",
    ajustes: "Paramètres",
    perfil: "Profil",

    // General / Dashboard
    bienvenida: "Bienvenue sur votre tableau de bord client",
    misViviendas: "Mes Propriétés",
    serviciosExtras: "Services Extras",
    cerrarSesion: "Se déconnecter",
    logout: "Se déconnecter",
    noHayDatos: "Aucun enregistrement disponible.",
    cambiarIdioma: "Langue",
    verDetalles: "Voir les détails",
    estadoPendiente: "En attente",
    estadoAprobado: "Approuvé",
    estadoCompletado: "Terminé",
    solicitarExtra: "Demander un service extra",
    totalPagar: "Total à payer",
    direccion: "Adresse",
    cargandoPanel: "Chargement du tableau de bord...",
    panelDeControl: "Panneau de configuration",
    dashboardCliente: "Tableau de bord client",
    operativo: "Opérationnel",
    trabajosExtrasDisponibles: "Travaux extra disponibles !",
    tienes: "Vous avez",
    trabajosRegistrados: "travaux ou rapports extra enregistrés.",
    trabajoExtraFactura: "Travail extra / Facture",
    verDetallesFotosFacturas: "Voir les détails et les photos dans les factures",
    verFactura: "Voir la facture →",
    alertas: "Alertes",
    inspeccionesDiarias: "Inspections quotidiennes",
    configuracionSeguridadNotificaciones: "Paramètres de sécurité et de notifications",
    lun: "Lun",
    mar: "Mar",
    mie: "Mer",
    jue: "Jeu",
    vie: "Ven",
    sab: "Sam",
    dom: "Dim",

    // Create Invoice
    tituloNuevaFactura: "Nouvelle facture / Extra",
    errorSeleccionarCliente: "Sélectionnez un client.",
    errorSeleccionarVivienda: "Sélectionnez une propriété.",
    errorIntroducirImporte: "Entrez le montant.",
    errorCreandoFactura: "Erreur lors de la création de la facture",
    facturaCreadaCorrectamente: "Facture créée avec succès",
    cliente: "Client",
    seleccionaCliente: "Sélectionner un client...",
    vivienda: "Propriété",
    seleccionaVivienda: "Sélectionner une propriété...",
    fecha: "Date",
    concepto: "Concept",
    placeholderConcepto: "Description du service...",
    importe: "Montant",
    btnCrearFactura: "Créer la facture",

    // Perfil Cliente
    clienteDashboardCargando: "Chargement du profil...",
    clienteDashboardNoEncontrado: "Profil client introuvable.",
    clientePerfilTitulo: "Mon Profil",
    clienteDashboardNombre: "Nom",
    clienteDashboardEmail: "E-mail",
    clienteDashboardTelefono: "Téléphone",

    // Configuration & Security
    configuracionYSeguridad: "Configuration et Sécurité",
    volver: "← Retour",
    preferenciasNotificacion: "Préférences de notification",
    notifPushTitulo: "Notifications Push",
    notifPushSub: "Recevez des avis immédiats dans l'application concernant vos inspections.",
    resumenCorreoTitulo: "Résumé par e-mail",
    resumenCorreoSub: "Recevez des rapports et des factures directement dans votre e-mail.",
    alertasCriticasTitulo: "Alertes d'incidents critiques",
    alertasCriticasSub: "Avis urgents d'incidents graves détectés dans les propriétés.",
    seguridadCuenta: "Sécurité du compte",
    autenticacionDosPasosTitulo: "Authentification à deux facteurs (2FA)",
    autenticacionDosPasosSub: "Ajoutez un niveau de sécurité supplémentaire lors de la connexion.",
    contrasena: "Mot de passe",
    ultimoCambioContrasena: "Dernière modification il y a plus de 30 jours",
    cambiar: "Modifier",
    alertaCambiarContrasena: "Fonction de modification du mot de passe",
    cambiosGuardados: "✓ Modifications enregistrées",
    guardarPreferencias: "Enregistrer les préférences",

    // Contracts List
    clienteListaTitulo: "Mes Contrats",
    cargandoContratos: "Chargement des contrats...",
    usuarioNoAutenticado: "Utilisateur non authentifié.",
    errorIdentificarCliente: "Impossible d'identifier le client associé.",
    errorCargandoContratos: "Erreur lors du chargement des contrats.",
    errorInesperadoContratos: "Erreur inattendue lors du chargement des contrats.",
    reintentar: "Réessayer",
    clienteListaVacio: "Vous n'avez aucun contrat enregistré.",
    servicioContratado: "Service contractuel",

    // View Contract Individual & PDF Generation
    contratoNoEncontrado: "Contrat introuvable",
    clienteContratoCargando: "Chargement du contrat...",
    noSePudoCargarContrato: "Impossible de charger le contrat",
    compruebaTuConexion: "Vérifiez votre connexion",
    clienteContratoTitulo: "Contrat du Client",
    clienteContratoDatosCliente: "Données du Client",
    nombre: "Nom",
    telefono: "Téléphone",
    clienteContratoDetalles: "Détails du Contrat",
    tipoServicio: "Type de service : Tous les",
    dias: "jours",
    precioMensual: "Prix mensuel",
    fechaInicio: "Date de début",
    estado: "Statut",
    firmado: "Signé",
    pendienteFirma: "En attente de signature",
    verContratoAntesFirmar: "📄 Voir le contrat avant de signer",
    firmaDelCliente: "Signature du Client",
    verCambiarFirma: "Voir / Modifier la signature",
    enviarAlAdminBtn: "📤 Envoyer le contrat à l'Admin",
    enviando: "Envoi en cours...",
    verContratoFirmadoPdf: "📄 Voir le contrat signé (PDF)",
    alertaDebesFirmar: "Vous devez signer le contrat avant de l'envoyer.",
    alertaErrorAdmin: "Erreur lors de la notification de l'administrateur : ",
    alertaContratoEnviado: "Contrat signé envoyé à l'administrateur !",
    alertaNoPdfAdmin: "L'administrateur n'a pas encore généré le PDF.",
    clienteAccesoDenegado: "Accès refusé ou contrat introuvable.",
    clienteContratoDireccion: "Adresse",

    // PDF Generation
    pdfTitulo: "CONTRAT DE PRESTATION DE SERVICES",
    pdfNombreCliente: "Client",
    pdfDireccion: "Adresse",
    pdfTelefono: "Téléphone",
    pdfDetallesServicio: "DÉTAILS DU SERVICE",
    pdfTipoServicio: "Fréquence",
    contratoCadaDias: "Tous les",
    pdfFechaInicio: "Date de début",
    pdfPrecioMensual: "Prix mensuel",
    pdfCondiciones: "CONDITIONS",
    pdfCondicionesTexto: "Le prestataire s'engage à effectuer les inspections et services convenus selon la fréquence établie, en conservant la confidentialité et la rigueur professionnelle.",
    pdfFirmaCliente: "Signature du Client",
    pdfGenerado: "PDF généré et enregistré avec succès !",
    pdfGenerando: "Génération du PDF...",
    pdfGenerar: "Générer et Enregistrer le PDF",
    errorSubirPdfStorage: "Erreur lors du téléchargement du PDF vers Storage : ",
    errorGenerarPdf: "Erreur lors de la génération du PDF : ",

    // PDF Viewer
    pdfCargando: "Chargement du PDF...",
    pdfNoGenerado: "Aucun fichier PDF n'a encore été généré pour ce contrat.",
    pdfTituloVista: "Contrat",
    pdfVolver: "Retour",
    pdfTituloIframe: "Visionneuse de Contrat",
    pdfAbrirNuevaPestana: "Ouvrir dans un nouvel onglet",

    // Signature Drawing
    firmaDelClienteTitulo: "Signature du Client",
    instruccionesFirma: "Dessinez votre signature avec votre doigt dans le cadre blanc :",
    limpiar: "🗑️ Effacer",
    guardarFirmaBtn: "💾 Enregistrer la signature",
    alertaRealizarFirma: "Veuillez effectuer votre signature avant d'enregistrer.",
    alertaIdContratoValido: "Erreur : Aucun ID de contrat valide n'a été trouvé.",
    errorGuardandoFirma: "Erreur lors de l'enregistrement de la signature.",
    contratoFirmadoExito: "Contrat signé avec succès !",
    errorGuardandoFirmaDetalle: "Erreur lors de l'enregistrement de la signature : ",

    // View Invoice Individual
    facturaNoEncontrada: "Facture introuvable",
    volverSimple: "Retour",
    estadoPagada: "PAYÉE",
    estadoEnviadaCliente: "ENVOYÉE AU CLIENT",
    servicioInspeccion: "Service / Inspection",
    facturaLabel: "Facture",
    evidenciaDelTrabajo: "Preuve du travail",
    materialesUtilizados: "Matériaux utilisés :",
    tiempoEmpleado: "Temps passé :",
    fotografiasInspeccion: "Photographies d'inspection :",
    detalle: "Détail",
    base: "Sous-total",
    iva: "TVA",
    total: "Total",
    verPdf: "Voir le PDF",
    noPdfGenerado: "Aucun PDF généré pour cette facture pour le moment.",

    // Invoices List
    misFacturasTitulo: "Mes Factures",
    cargandoFacturas: "Chargement des factures...",
    noHayFacturasRegistradas: "Aucune facture enregistrée.",
    estadoCancelada: "ANNULÉE",
    estadoTrabajoCompletado: "TRAVAIL TERMINÉ",
    estadoPendienteRevision: "EN ATTENTE DE RÉVISION",

    // Inspections List
    cargandoListado: "Chargement de la liste...",
    misInspeccionesInformesTitulo: "Mes Inspections et Rapports",
    errorPerfilClienteAsociado: "Profil client associé introuvable.",
    errorCargarDatos: "Une erreur s'est produite lors du chargement des données.",
    noHayInspeccionesInformes: "Aucune inspection ou rapport disponible.",
    servicioExtraTrabajo: "🛠️ Service Extra / Travail",
    inspeccionLabel: "📋 Inspection",
    informeDisponible: "Rapport disponible",
    detalleLabel: "Détail :",
    verDetalleFlecha: "Voir le détail →",
    extraBadge: "⚡ EXTRA",

    // View Inspection / Report
    cargandoInformacion: "Chargement des informations...",
    volverMisInformes: "← Retour à mes rapports",
    informeNoEncontradoPermisos: "Rapport introuvable ou vous n'avez pas l'autorisation de le voir.",
    errorConexionCargarInformacion: "Erreur de connexion lors du chargement des informations.",
    confirmarBorrarInforme: "Êtes-vous sûr de vouloir supprimer ce rapport de votre liste ?",
    informeEliminadoExito: "Rapport supprimé avec succès.",
    errorEliminarInforme: "Impossible de supprimer le rapport.",
    informeLabel: "Rapport",
    ubicacionVivienda: "Emplacement / Propriété",
    direccionNoEspecificada: "Adresse non spécifiée",
    descripcionTrabajoObservaciones: "Description du travail / Observations",
    sinObservacionesRegistradas: "Aucune observation enregistrée.",
    materialesUsados: "Matériaux utilisés :",
    tiempoEmpleadoLabel: "Temps passé :",
    fotografiasAdjuntas: "Photographies jointes",
    noHayFotografiasInforme: "Aucune photographie jointe à ce rapport.",
    verInformePdf: "📄 Voir le rapport PDF",
    borrarEsteInforme: "🗑️ Supprimer ce rapport",
    fotoAmpliada: "Photo agrandie",
    cerrar: "Fermer",
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  // Recuperar idioma guardado en localStorage o usar 'es' por defecto
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('app_idioma') || 'es';
  });

  useEffect(() => {
    localStorage.setItem('app_idioma', language);
  }, [language]);

  // Función para traducir claves. Ej: t('clientes')
  const t = (key) => {
    return translations[language]?.[key] || translations['es']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

// Hook personalizado para usar el contexto de idioma fácilmente
export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage debe ser usado dentro de un LanguageProvider');
  }
  return context;
};
