import React, { createContext, useContext, useState } from 'react';

const translations = {
  es: {
    // Generales / Dashboard
    bienvenida: "Bienvenido a tu panel de cliente",
    misViviendas: "Mis Viviendas",
    serviciosExtras: "Servicios Extras",
    facturas: "Facturas y Pagos",
    perfil: "Mi Perfil",
    cerrarSesion: "Cerrar Sesión",
    noHayDatos: "No hay registros disponibles.",
    cambiarIdioma: "Idioma",
    verDetalles: "Ver Detalles",
    estadoPendiente: "Pendiente",
    estadoAprobado: "Aprobado",
    estadoCompletado: "Completado",
    solicitarExtra: "Solicitar Servicio Extra",
    totalPagar: "Total a Pagar",
    direccion: "Dirección",
    cargandoPanel: "Cargando Panel...",
    panelDeControl: "Panel de Control",
    dashboardCliente: "Dashboard Cliente",
    operativo: "Operativo",
    trabajosExtrasDisponibles: "¡Trabajos Extras Disponibles!",
    tienes: "Tienes",
    trabajosRegistrados: "trabajos o informes extras registrados.",
    trabajoExtraFactura: "Trabajo Extra / Factura",
    verDetallesFotosFacturas: "Ver detalles y fotos en facturas",
    verFactura: "Ver Factura →",
    inspecciones: "Inspecciones",
    alertas: "Alertas",
    viviendas: "Viviendas",
    inspeccionesDiarias: "Inspecciones Diarias",
    configuracionSeguridadNotificaciones: "Configuración de Seguridad y Notificaciones",
    lun: "Lun",
    mar: "Mar",
    mie: "Mié",
    jue: "Jue",
    vie: "Vie",
    sab: "Sáb",
    dom: "Dom",

    // Configuración y Seguridad
    configuracionYSeguridad: "Configuración y Seguridad",
    volver: "← Volver",
    preferenciasNotificacion: "Preferencias de Notificación",
    notifPushTitulo: "Notificaciones Push",
    notifPushSub: "Recibe avisos inmediatos en la app sobre tus inspecciones.",
    resumenCorreoTitulo: "Resumen por Correo",
    resumenCorreoSub: "Recibe informes y facturas directamente en tu email.",
    alertasCriticasTitulo: "Alertas de Incidencias Críticas",
    alertasCriticasSub: "Avisos urgentes de incidencias graves detectadas en viviendas.",
    seguridadCuenta: "Seguridad de la Cuenta",
    autenticacionDosPasosTitulo: "Autenticación en 2 Pasos (2FA)",
    autenticacionDosPasosSub: "Añade un nivel extra de seguridad al iniciar sesión.",
    contrasena: "Contraseña",
    ultimoCambioContrasena: "Último cambio hace más de 30 días",
    cambiar: "Cambiar",
    alertaCambiarContrasena: "Función para cambiar contraseña",
    cambiosGuardados: "✓ Cambios Guardados",
    guardarPreferencias: "Guardar Preferencias",

    // Lista de Contratos
    clienteListaTitulo: "Mis Contratos",
    cargandoContratos: "Cargando contratos...",
    usuarioNoAutenticado: "Usuario no autenticado.",
    errorIdentificarCliente: "No se pudo identificar el cliente asociado.",
    errorCargandoContratos: "Error cargando contratos.",
    errorInesperadoContratos: "Error inesperado cargando contratos.",
    reintentar: "Reintentar",
    clienteListaVacio: "No tienes contratos registrados.",
    servicioContratado: "Servicio contratado",

    // Ver Contrato Individual
    contratoNoEncontrado: "Contrato no encontrado",
    clienteContratoCargando: "Cargando contrato...",
    noSePudoCargarContrato: "No se pudo cargar el contrato",
    compruebaTuConexion: "Comprueba tu conexión",
    clienteContratoTitulo: "Contrato del Cliente",
    clienteContratoDatosCliente: "Datos del Cliente",
    nombre: "Nombre",
    telefono: "Teléfono",
    clienteContratoDetalles: "Detalles del Contrato",
    tipoServicio: "Tipo de servicio: Cada",
    dias: "días",
    precioMensual: "Precio mensual",
    fechaInicio: "Fecha inicio",
    estado: "Estado",
    firmado: "Firmado",
    pendienteFirma: "Pendiente de firma",
    verContratoAntesFirmar: "📄 Ver contrato antes de firmar",
    firmaDelCliente: "Firma del Cliente",
    verCambiarFirma: "Ver / Cambiar Firma",
    enviarAlAdminBtn: "📤 Enviar contrato al Admin",
    enviando: "Enviando...",
    verContratoFirmadoPdf: "📄 Ver contrato firmado (PDF)",
    alertaDebesFirmar: "Debes firmar el contrato antes de enviarlo.",
    alertaErrorAdmin: "Error notificando al administrador: ",
    alertaContratoEnviado: "¡Contrato firmado enviado al administrador!",
    alertaNoPdfAdmin: "El administrador aún no ha generado el PDF.",
  },
  en: {
    // General / Dashboard
    bienvenida: "Welcome to your client dashboard",
    misViviendas: "My Properties",
    serviciosExtras: "Extra Services",
    facturas: "Invoices & Payments",
    perfil: "My Profile",
    cerrarSesion: "Log Out",
    noHayDatos: "No records available.",
    cambiarIdioma: "Language",
    verDetalles: "View Details",
    estadoPendiente: "Pending",
    estadoAprobado: "Approved",
    estadoCompletado: "Completed",
    solicitarExtra: "Request Extra Service",
    totalPagar: "Total Due",
    direccion: "Address",
    cargandoPanel: "Loading Dashboard...",
    panelDeControl: "Control Panel",
    dashboardCliente: "Client Dashboard",
    operativo: "Operational",
    trabajosExtrasDisponibles: "Extra Jobs Available!",
    tienes: "You have",
    trabajosRegistrados: "extra jobs or reports registered.",
    trabajoExtraFactura: "Extra Job / Invoice",
    verDetallesFotosFacturas: "View details and photos in invoices",
    verFactura: "View Invoice →",
    inspecciones: "Inspections",
    alertas: "Alerts",
    viviendas: "Properties",
    inspeccionesDiarias: "Daily Inspections",
    configuracionSeguridadNotificaciones: "Security and Notification Settings",
    lun: "Mon",
    mar: "Tue",
    mie: "Wed",
    jue: "Thu",
    vie: "Fri",
    sab: "Sat",
    dom: "Sun",

    // Configuration & Security
    configuracionYSeguridad: "Configuration & Security",
    volver: "← Back",
    preferenciasNotificacion: "Notification Preferences",
    notifPushTitulo: "Push Notifications",
    notifPushSub: "Receive immediate notices in the app about your inspections.",
    resumenCorreoTitulo: "Email Summary",
    resumenCorreoSub: "Receive reports and invoices directly in your email.",
    alertasCriticasTitulo: "Critical Incident Alerts",
    alertasCriticasSub: "Urgent notices of severe incidents detected in properties.",
    seguridadCuenta: "Account Security",
    autenticacionDosPasosTitulo: "Two-Factor Authentication (2FA)",
    autenticacionDosPasosSub: "Add an extra level of security when logging in.",
    contrasena: "Password",
    ultimoCambioContrasena: "Last changed more than 30 days ago",
    cambiar: "Change",
    alertaCambiarContrasena: "Password change feature",
    cambiosGuardados: "✓ Changes Saved",
    guardarPreferencias: "Save Preferences",

    // Contracts List
    clienteListaTitulo: "My Contracts",
    cargandoContratos: "Loading contracts...",
    usuarioNoAutenticado: "User not authenticated.",
    errorIdentificarCliente: "Could not identify the associated client.",
    errorCargandoContratos: "Error loading contracts.",
    errorInesperadoContratos: "Unexpected error loading contracts.",
    reintentar: "Retry",
    clienteListaVacio: "You have no registered contracts.",
    servicioContratado: "Contracted service",

    // View Contract Individual
    contratoNoEncontrado: "Contract not found",
    clienteContratoCargando: "Loading contract...",
    noSePudoCargarContrato: "Could not load the contract",
    compruebaTuConexion: "Check your connection",
    clienteContratoTitulo: "Client Contract",
    clienteContratoDatosCliente: "Client Details",
    nombre: "Name",
    telefono: "Phone",
    clienteContratoDetalles: "Contract Details",
    tipoServicio: "Service type: Every",
    dias: "days",
    precioMensual: "Monthly price",
    fechaInicio: "Start date",
    estado: "Status",
    firmado: "Signed",
    pendienteFirma: "Pending signature",
    verContratoAntesFirmar: "📄 View contract before signing",
    firmaDelCliente: "Client Signature",
    verCambiarFirma: "View / Change Signature",
    enviarAlAdminBtn: "📤 Send contract to Admin",
    enviando: "Sending...",
    verContratoFirmadoPdf: "📄 View signed contract (PDF)",
    alertaDebesFirmar: "You must sign the contract before sending it.",
    alertaErrorAdmin: "Error notifying the administrator: ",
    alertaContratoEnviado: "Signed contract sent to the administrator!",
    alertaNoPdfAdmin: "The administrator has not generated the PDF yet.",
  },
  fr: {
    // Général / Tableau de bord
    bienvenida: "Bienvenue sur votre tableau de bord client",
    misViviendas: "Mes Propriétés",
    serviciosExtras: "Services Supplémentaires",
    facturas: "Factures et Paiements",
    perfil: "Mon Profil",
    cerrarSesion: "Se Déconnecter",
    noHayDatos: "Aucun enregistrement disponible.",
    cambiarIdioma: "Langue",
    verDetalles: "Voir les détails",
    estadoPendiente: "En attente",
    estadoAprobado: "Approuvé",
    estadoCompletado: "Terminé",
    solicitarExtra: "Demander un service supplémentaire",
    totalPagar: "Total à payer",
    direccion: "Adresse",
    cargandoPanel: "Chargement du tableau de bord...",
    panelDeControl: "Panneau de contrôle",
    dashboardCliente: "Tableau de bord client",
    operativo: "Opérationnel",
    trabajosExtrasDisponibles: "Travaux supplémentaires disponibles !",
    tienes: "Vous avez",
    trabajosRegistrados: "travaux ou rapports supplémentaires enregistrés.",
    trabajoExtraFactura: "Travail supplémentaire / Facture",
    verDetallesFotosFacturas: "Voir les détails et photos dans les factures",
    verFactura: "Voir la facture →",
    inspecciones: "Inspections",
    alertas: "Alertes",
    viviendas: "Propriétés",
    inspeccionesDiarias: "Inspections quotidiennes",
    configuracionSeguridadNotificaciones: "Paramètres de sécurité et de notification",
    lun: "Lun",
    mar: "Mar",
    mie: "Mer",
    jue: "Jeu",
    vie: "Ven",
    sab: "Sam",
    dom: "Dim",

    // Configuration & Sécurité
    configuracionYSeguridad: "Configuration & Sécurité",
    volver: "← Retour",
    preferenciasNotificacion: "Préférences de notification",
    notifPushTitulo: "Notifications push",
    notifPushSub: "Recevez des avis immédiats dans l'application sur vos inspections.",
    resumenCorreoTitulo: "Résumé par e-mail",
    resumenCorreoSub: "Recevez des rapports et factures directement dans votre e-mail.",
    alertasCriticasTitulo: "Alertas d'incidents critiques",
    alertasCriticasSub: "Avis urgents d'incidents graves détectés dans les logements.",
    seguridadCuenta: "Sécurité du compte",
    autenticacionDosPasosTitulo: "Authentification à 2 facteurs (2FA)",
    autenticacionDosPasosSub: "Ajoutez un niveau de sécurité supplémentaire lors de la connexion.",
    contrasena: "Mot de passe",
    ultimoCambioContrasena: "Dernière modification il y a plus de 30 jours",
    cambiar: "Modifier",
    alertaCambiarContrasena: "Fonction de changement de mot de passe",
    cambiosGuardados: "✓ Modifications enregistrées",
    guardarPreferencias: "Enregistrer les préférences",

    // Liste des Contrats
    clienteListaTitulo: "Mes Contrats",
    cargandoContratos: "Chargement des contrats...",
    usuarioNoAutenticado: "Utilisateur non authentifié.",
    errorIdentificarCliente: "Impossible d'identifier le client associé.",
    errorCargandoContratos: "Erreur lors du chargement des contrats.",
    errorInesperadoContratos: "Erreur inattendue lors du chargement des contrats.",
    reintentar: "Réessayer",
    clienteListaVacio: "Vous n'avez aucun contrat enregistré.",
    servicioContratado: "Service souscrit",

    // Vue Contrat Individuel
    contratoNoEncontrado: "Contrat non trouvé",
    clienteContratoCargando: "Chargement du contrat...",
    noSePudoCargarContrato: "Impossible de charger le contrat",
    compruebaTuConexion: "Vérifiez votre connexion",
    clienteContratoTitulo: "Contrat Client",
    clienteContratoDatosCliente: "Détails du client",
    nombre: "Nom",
    telefono: "Téléphone",
    clienteContratoDetalles: "Détails du contrat",
    tipoServicio: "Type de service : Tous les",
    dias: "jours",
    precioMensual: "Prix mensuel",
    fechaInicio: "Date de début",
    estado: "Statut",
    firmado: "Signé",
    pendienteFirma: "En attente de signature",
    verContratoAntesFirmar: "📄 Voir le contrat avant de signer",
    firmaDelCliente: "Signature du client",
    verCambiarFirma: "Voir / Modifier la signature",
    enviarAlAdminBtn: "📤 Envoyer le contrat à l'Admin",
    enviando: "Envoi en cours...",
    verContratoFirmadoPdf: "📄 Voir le contrat signé (PDF)",
    alertaDebesFirmar: "Vous devez signer le contrat avant de l'envoyer.",
    alertaErrorAdmin: "Erreur lors de la notification de l'administrateur : ",
    alertaContratoEnviado: "Contrat signé envoyé à l'administrateur !",
    alertaNoPdfAdmin: "L'administrateur n'a pas encore généré le PDF.",
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(localStorage.getItem('app_lang') || 'es');

  const changeLanguage = (newLang) => {
    setLang(newLang);
    localStorage.setItem('app_lang', newLang);
  };

  const t = (key) => {
    return translations[lang]?.[key] || translations['es'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useTranslation = () => useContext(LanguageContext);
export const useLanguage = () => useContext(LanguageContext);
